### ISSUE TITLE
Revise Training Section

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#10]
#### Description of Issue: ####

- Identify the target audience and revise accordingly  
- Clarify whether the recommended training for PACS projects applies to only Federal Government team members
- Use consistent terms for roles
- Restructure to improve the logical flow of information and revise content for clarity

#### Detailed Suggestions and Questions To Consider: ####

- Restructure this section. Change “What Training Is Required?” to **Training** (level 1 heading) and add 3 subsections:

  o **Technical Roles and Responsibilities** (level 2 heading). State briefly each role’s responsibilities.
  o **Recommended Training** (level 2 heading).  State briefly the recommended training for each role. 
  o **Opportunities** (level 2 heading). (Renamed from “Where Can I Get Training?”) 

- The target audience for this section is unclear.  Is the audience government only?  Does it consist of “physical access control system architects, engineers/implementers, and project managers,” as stated in the Playbook introduction?  Do the roles, “IT support personnel, administrators, operators, and technicians,” all belong to the “engineers/implementers” group?
- Add a purpose statement upfront.  For example:  “This section identifies recommended training for Federal Government team members who support PACS implementation projects.”  If appropriate, add:  “Contractors should possess the required certifications and skills at contract start; however, continuous training and development for contractors is recommended.”  (Correct for accuracy, as needed.)
- Provide links to where an agency user can buy or attend the training options (aligned with submitting their annual training plan and using their annual training budget).  
- Identify what, if any, additional training would be needed if “agency IT support personnel and application administrators…are trained by individual PACS manufacturers.”
- How would an operator get this training:  “Operator training should be tailored to [an] agency’s policies and procedures, the individual’s role within [an] agency, and [the] facility’s PACS configuration”? 
- The "project manager" is mentioned in the first sentence of this section.  Does the PM fulfill the “procurement” role? What training is required?
- Would a CPP apply (i.e., those who manage security programs) to a role on a PACS implementation project?
- What PACS implementation role would need a CSPM—a PACS architect?
- Remove statements that don’t add value (for example, “the team as a whole must have a wide range of knowledge and experience” and “some training will be general,” etc.). 
- Tighten content; remove filler.
- Remove technical details about PACS covered in other sections.

#### Link to Additional Guidelines: ####

- https://github.com/GSA/ficam-pacs/blob/staging/README.md

#### Link to Navigation (Outline) Issue: ####

- https://github.com/GSA/ficam-pacs/issues/2

#### Link to the Content Page for Contributors: ####

- https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/train/

**Comment by ryancdickson** [comment]
Comment adjudicated.
