### ISSUE TITLE
Revise Introduction Section

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#12]
#### Description of Issue: ####

- Revise the “Introduction” section to briefly state the PACS Playbook’s purpose, target audience, and major topics list. 

#### Detailed Suggestions: ####

- Delete the “Background” section.
- Delete the “Physical Access Control System Playbook” title.  (The Playbook title will appear in Federalist web view.)
- Revise the second paragraph to read:  “This Playbook will help physical access control systems architects, engineers, and project managers implement physical access control systems (PACS) that work with Personal Identity Verification (PIV) cards. It will walk you through how to:”
- Revise the bullet list to read:
o Understand enterprise physical access systems
o Align facility security level (FSL) and authentication
o Procure a PACS
o Identify training
o Locate related standards, policies, and guidance”

#### Link to Additional Guidelines: ####

https://github.com/GSA/ficam-pacs/blob/staging/README.md

#### Link to Navigation (Outline) Issue: ####

https://github.com/GSA/ficam-pacs/issues/2

#### Link to the Content Page for Contributors: ####

https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/

**Comment by ryancdickson** [comment]
Comment adjudicated.
