### ISSUE TITLE
Remove PIV and PIV-I Considerations Section 

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#13]
#### Description of Issue: ####

- Suggest removing the PIV and PIV-I Considerations section  
- In the “_Aligning Facility Security Level and Authentication_” section, link to resources that provide detailed PIV information (and PIV-I if needed). (Some links provided below.)
- Provide a brief PIV discussion (including PIV-I if needed), as it relates to Enterprise Physical Access Control Systems in the “_Aligning Facility Security Level and Authentication_” section 

#### Details of Issue: ####

- Remove the PIV and PIV-I Considerations section
- Provide a brief  PIV discussion (including PIV-I if needed) as it relates to Enterprise Physical Access Control Systems in the “_Aligning Facility Security Level and Authentication_” section, under the ACC Playbook’s former subtitle, “_What Authentication Mechanisms Are Available?_” (Suggest subtitle change to “_Determine Authentication Factors_.”)  Some statements could be extracted from the ACC Playbook’s “PIV and PIV-I Considerations” for this discussion.
- Link to resources that provide detailed PIV information (and PIV-I if needed) in the “_Aligning Facility Security Level and Authentication_” section, “_Determine Authentication Factors_” subsection.  For example: 
o www.piv.idmanagement.gov
- Under the “_Aligning Facility Security Level and Authentication_” section, “_Determine Authentication Factors_” subsection, provide links to PIV-related standards and policies if needed. (Footnotes may be used to provide these links.) For example, use these links:
o https://piv.idmanagement.gov/#where-can-i-find-the-standards)
o https://csrc.nist.gov/projects/piv/piv-standards-and-supporting-documentation
o https://csrc.nist.gov/Topics/Laws-and-Regulations/executive-documents/HSPD-12
- "Does PIV-I affect Federal agencies and employees?" section:  PIV-I advantages aren't relevant to PACS focus.
- Information on PIV card readers and availability through the GSA’s Approved Products List (APL) should be mentioned in the Playbook (location – TBD); however, differences between PIV and PIV-I readers shouldn't be included.
- Move specific links (OMB Memoranda, etc.) to the “_Standards and Policies_” section, unless there is an important reason to call out a policy/standard.  
- When citing documents, use only document titles in the main body.  Provide full citations in the “_Standards and Policies_” section. 

#### Link to Additional Guidelines: ####

- https://github.com/GSA/ficam-pacs/blob/staging/README.md

#### Link to the Content Page for Contributors: ####

- https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/pivandpivi/

**Comment by clstmbrly** [comment]
This section has been removed from the PACS Playbook.

**Comment by ryancdickson** [comment]
Comment adjudicated.
