### ISSUE TITLE
Remove Deploy a PACS Section

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#14]
#### Description of Issue: ####

- Suggest removing the “Deploy a PACS” section 
- Move the referenced standards information to the “_Aligning Facility Security Level and Authentication_” section

#### Detailed Suggestions: ####

- Remove the “Deploy a PACS” section
- Move the referenced standards (FIPS 199, 200, and NIST SP 800-53, Revision 4, etc.) to the “_Aligning Facility Security Level and Authentication_” section, where security categorization and security controls are discussed.  Simply state what the agency needs to do to comply with these standards.  
- Who is the target audience for the information about NIST SP 800-171, "_Protecting Controlled Unclassified Information in Nonfederal Information Systems and Organizations_”?  Suggest removing this information.
- For referenced documents cited in main body, use only identifiers and titles (e.g., FIPS 199, “Standards for Security Categorization of Federal Information and Information Systems”). Full citations will be included in a "Standards and Policies" section.

#### Link to Additional Guidelines: ####

- https://github.com/GSA/ficam-pacs/blob/staging/README.md

#### Link to Navigation (Outline) Issue:   ####

https://github.com/GSA/ficam-pacs/issues/2

#### Link to the Content Page for Contributors: ####

- https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/deploy/

**Comment by clstmbrly** [comment]
This section has been removed from the PACS Playbook.

**Comment by ryancdickson** [comment]
Comment adjudicated.
