### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-pacs#15]
#### Description of Issue: ####
Add search

#### Details of Issue: ####

- The site needs to be live
- the analytics are updated
- the site is added to the _idmprod_ search search.gov
- the search string added to config
- search added to the top level navigation - replaces "view site code"

See branch in piv-guides repo for example (not live) of the search addition

**Comment by ryancdickson** [comment]
Closing issue. We're just waiting on resolution of the indexing issue detailed in #28.
