### ISSUE TITLE
Suggest adding ISC training links to Training page

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-pacs#16]
#### Description of Issue: ####
On the draft training information page - add information and cross-reference (link) to the interagency security council training site

#### Details of Issue: ####
There are online training modules maintained by DHS and interagency security council (ISC)
Some of the training modules are available for both federal and non-federal 

#### References (Docs, Links, Files): ####
https://www.dhs.gov/interagency-security-committee-training

**Comment by ryancdickson** [comment]
Comment adjudicated.
