### ISSUE TITLE
Concepts are confused: Standalone vs. Enterprise; legacy credentials vs. FICAM compliant

### ISSUE THREAD

**Issue by sph2sail** [GSA/ficam-pacs#18]
**Description:**
This page should separate the concepts of PACS Technology from Standalone vs. Enterprise PACS deployment.  These are three separate topic areas.  Many PACS vendors, prior to FICAM compliance, supported both standalone and the ability to scale that capability to Enterprise wide access control.  PACS Technology speaks to FICAM compliance (using strong auth from PIV/PIV-I/CIV) vs. traditional technologies (ISOProx, iCLASS, Indala, magstripe, barcode, etc.).  Here may cover the changes to PACS technology to support strong auth with PKI, revocation status through CRL, etc.

**Issues:**
1. Instead of "Types of PACS" I would recommend language like "Deployment Models for PACS".  This gets to the heart of standalone vs. Enterprise deployment.  It allows discussion of the, still ongoing, needs for standalone (SCIF, SBU but operationally sensitive enough of an area to warrant local control) vs. enterprise overarching goals (Insider threat, CDM, who is where right now).
1. PACS Technology should be described to incorporate "deployed technologies" vs. FICAM compliant technologies.  This allows the introduction of:
  1. Deployed technologies
    - Architectures
    - Technology
    - Capabilities and risks
  1. FICAM compliant technologies
    - Topologies
    - Technology
    - Capabilities and risks
1. Then discuss migration objectives of FICAM for PACS.
  1. Discussion of standalone vs. enterprise within the context of FICAM
    - Support for Insider Threat, CDM, etc.
  1. Discussion on technology selection
    - FICAM compliance
    - Directives/Memoranda/Standards/Guidelines for compliance

**Comment by sph2sail** [comment]
I wish I could edit this post.  First attempt at markdown.  Sorry I messed it up.

(2)&(3) are sub to (1).
(4) should be (2).
(5)&(6) should be sub to (4)/(2).
(7) should be (3).

**Comment by ryancdickson** [comment]
@sph2sail - Thanks for your review and comments - all helpful context!
