### ISSUE TITLE
Need to Decide on Navigation Menu Items

### ISSUE THREAD

**Issue by djpackham** [GSA/ficam-pacs#2]
#### Description of Issue: ####
The minimum viable navigation items for the PACS playbook need to be decided on

#### Details of Issue: ####
Current navigation items are:
- Introduction
- Basics of a PACS
- Getting Started
- Use Cases
- FAQ
- Contribute

#### References (Docs, Links, Files): ####
- https://github.com/GSA/ficam-pacs/blob/staging/_config.yml

#### Link to the Content Page for Contributors: ####
- https://github.com/GSA/ficam-pacs/blob/staging/_config.yml

**Comment by clstmbrly** [comment]
The PACS Playbook's current navigation is based on the original ACC Playbook's sequence of major topics.  We also added a "Standards and Policies" section.  The section titles have been slightly edited for brevity.  

Conversion to Markdown files is in process.

- Introduction
- Determine Facility Risk
- Select Authentication Mechanism
- Understand Enterprise PACS
- PIV and PIV-I Considerations
- Procure an Approved PACS
- Deploy a PACS
- Training
- Standards and Policies

[https://github.com/GSA/ficam-pacs/tree/pacs-playbook/pages](url)

@lachellel @djpackham

**Comment by clstmbrly** [comment]
The suggested, revised navigation (outline) for the PACS Playbook is: 

- Introduction (_no title; content only_)
- Enterprise Physical Access Control Systems
- Aligning Facility Security Level (FSL) and Authentication
- Procurements
- Training
- Standards and Policies (i.e., Referenced Documents)

In addition, we recommend removing the following 2 sections:

- PIV and PIV-I Considerations.  Existing resources for this information may be cited in other sections, as needed.
- Deploy a PACS.  This standards-focused information may be migrated to other sections, as needed (e.g., “Enterprise Physical Access Control Systems” or “Procurements” sections).

#### Link to the Content Page for Contributors: ####

https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/

**If these changes are agreed upon, the Federalist Live Preview's navigation sidebar will be updated.**

**Comment by ryancdickson** [comment]
Comment adjudicated.
