### ISSUE TITLE
Migrate ACC Playbook to GitHub Markdown as “PACS Playbook” for Community Collaboration

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#3]
#### Description of Issue: ####
The ACC Playbook needs to be migrated to GitHub Markdown to become the "PACS Playbook" to allow for continued development.

#### Details of Issue: ####
A number of organizations have worked on this Playbook over time.  The Playbook's migration to GitHub Markdown will allow the community to openly collaborate and contribute to its further development.

#### If a New Page or Content is Needed, Expected Outcomes: ####
Revisions are needed.  New content may be needed.  Expected outcome is a clear, cohesive, well-written, and useful PACS guide.

#### Link to the Content Page for Contributors: ####
[https://github.com/GSA/ficam-pacs/tree/pacs-playbook/pages](url)

**Comment by clstmbrly** [comment]
@lachellel @djpackham The PACS Playbook sections cite many referenced documents (a number are outdated, etc., but I can fix that for the most part). I've started compiling the references into a separate Standards and Policies section (similar to what FICAM-Arch has).  Any preference for this method of handling cited sources over adding footnoted references to the bottom of each section?  Thanks:-)

**Comment by clstmbrly** [comment]
@lachellel @djpackham I've completed migrating the ACC Playbook to the "PACS Playbook" and converted all sections to Markdown.  Again, here is the current navigation:

- Introduction
- Determine Facility Risk
- Select Authentication Mechanism
- Understand Enterprise PACS
- PIV and PIV-I Considerations
- Procure an Approved PACS
- Deploy a PACS
- Training
- Standards and Policies

[https://github.com/GSA/ficam-pacs/tree/pacs-playbook/pages](url)

Please let me know if you see anything that needs to be changed.

**Comment by lachellel** [comment]
@clstmbrly the migration is done - we can close this issue.
