### ISSUE TITLE
Revise Enterprise Physical Access Control Systems Section

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#7]
#### Description of Issue: ####

- Update the "Enterprise Physical Access Control Systems" section with current information, practices, and graphics
- Restructure to improve the logical flow of information
- Revise content for succinctness and clarity

#### Detailed Suggestions: ####

- Revise with the target audience in mind
- Add a purpose statement upfront
- Structure titles and content for logical flow of information
- As needed, migrate pertinent information from the "_FICAM Roadmap_" to PACS PLaybook
- Update with current information and practices
- Revise content for succinctness and clarity
- Remove descriptions of outdated practices and all non-essential information
- Use bullets, steps, and checklists wherever possible (for example, use a bullet list of reasons to consider enterprise-wide physical access control systems, not “An Enterprise PACS management system can help reduce human error, reduce costs, and provide a unified view of all identities and their privileges.”) 
- Remove subjective statements (for example, “The ATO process can be costly and tedious and involves each PACS vendor, who may need to update or patch its software to fix security flaws.”) 
- Update/modernize graphics to use newer visuals and icons 
- Remove references to the FICAM Roadmap
- Don't include document reference details. (These will be included in a "_Standards and Policies_" section.)

#### Link to Additional Guidelines ####

https://github.com/GSA/ficam-pacs/blob/staging/README.md

#### Link to the Content Page for Contributors: ####

https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/enterprisepacs/

**Comment by clstmbrly** [comment]
**Corrected links:**

**Link to Additional Guidelines (README):**

(https://github.com/GSA/ficam-pacs/blob/staging/README.md)

**Link to the Content Page for Contributors:**
[](url)
**Link to the Content Page for Contributors:**

**Comment by clstmbrly** [comment]
Re-opening Issue

**Comment by ryancdickson** [comment]
Comment adjudicated.
