### ISSUE TITLE
Revise Procurements Sections

### ISSUE THREAD

**Issue by clstmbrly** [GSA/ficam-pacs#9]
#### Description of Issue: ####

Update the “Procurements” section:

- Consider rewording this section as FAQs
- Ensure that information is current
- Restructure to improve the logical flow of information and revise content for clarity
- Focus on federal agencies’ needs

#### Detailed Suggestions: ####

- Revise with the target audience in mind
- Add a purpose statement upfront 
- Link to the GSA’s [Approved Products List – PACS Products](https://www.idmanagement.gov/approved-products-list-pacs-products/) and consider rewording this section as FAQs
- Restructure subsections to improve the logical flow of information
- For the first section, combine “How Do I Buy a Compliant PACS?” with the content from “What is a GSA APL-Listed PACS?”
- Include lessons learned from federal agencies, as appropriate. 
- Remove non-essential information (for example, remove “Why Does My Agency Need This?” section)
- Tighten content and eliminate redundancies 
- Use bullets, steps, and checklists, as appropriate for FAQs
- Remove all vendor-focused information, including links to the FIPS 201 Evaluation Program webpage
- Change "IdentityManagement.gov" to "IDManagement.gov."

#### Link to Additional Guidelines (README): ####

https://github.com/GSA/ficam-pacs/blob/staging/README.md

#### Link to the Content Page for Contributors: ####

https://federalist-proxy.app.cloud.gov/preview/gsa/ficam-pacs/pacs-playbook/procure/

**Comment by ryancdickson** [comment]
Comment adjudicated.
